name: pruebaa
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.9.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #cupertino_icons: ^1.0.8
  camera: ^0.10.0  # Para acceder a la cámara
  image_picker: ^1.1.2  # Alternativa para seleccionar imágenes
  #tflite: ^1.1.2
  tflite_flutter: ^0.11.0
  image: ^4.3.0
  path_provider: ^2.1.3
  #permission_handler: ^10.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/models/diagnostico.tflite
    - assets/models/medir.tflite
    - assets/models/detection.tflite
    - assets/labels.txt
    - assets/images/

